# -*- coding: utf-8 -*-
"""text_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdRUV7ux0ox3mggxD_d8YDBko5qAeyAz
"""

import pandas as pd
from textblob import TextBlob

from google.colab import files
uploaded = files.upload()

import os
cwd = os.getcwd()
files = [f for f in os.listdir('.') if os.path.isfile(f)]
for f in files:
  print(f)

nd = pd.read_excel('news_data.xlsx')
#nd.head()
#nd.describe()
nf = []
for ln in nd:
    print(ln)
    words = ln.split("], [")
    nf.append(words)

df = pd.DataFrame(nf)

new_df = df.T
new_df.shape
new_df.columns=['Statements']
new_df['Statements']

def find_count(statmnt):
  count1=statmnt.split(" ")
  return len(count1)
new_df['stmt_count'] = new_df['Statements'].apply(find_count)


def getSubjectivity(statement):
    return TextBlob(statement).sentiment.subjectivity

def getPolarity(statement):
    return TextBlob(statement).sentiment.polarity

new_df['pol_textblob'] = new_df['Statements'].apply(getPolarity)
new_df['Subjectivity_textblob'] = new_df['Statements'].apply(getSubjectivity)

new_df

def get_score(val):
  if val > 0:
    return 'Postive'
  elif val < 0:
    return 'Negative'
  else:
    return 'Neutral'
new_df['pol_score'] = new_df['pol_textblob'].apply(get_score)
new_df.to_excel('analysis.xlsx')
new_df.describe()

"""85,1"""